// <auto-generated />
namespace PassionProject_N01338717.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Intials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intials));
        
        string IMigrationMetadata.Id
        {
            get { return "202002191424281_Intials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
