// <auto-generated />
namespace PassionProject_N01338717.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Initials1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initials1));
        
        string IMigrationMetadata.Id
        {
            get { return "202002192244254_Initials1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
